---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# The Python Programming Language: Functions

<br>
`add_numbers` is a function that takes two numbers and adds them together.

In [2]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

In [1]:
def add_numbers(a,b):
    return a+b

add_numbers(1,2)

3

<br>
`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [3]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


In [4]:
def add_numbers(x,y,z=None):
    if(z==None):
        return x+y
    else:
        return x+y+z
    
print(add_numbers(1,2))
print(add_numbers(1,2,5))

3
8


<br>
`add_numbers` updated to take an optional flag parameter.

In [5]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true!
3


In [8]:
def add_numbers(x,y,z=None,flag=False):
    if(flag):
        print("Flag is true!")
    if(z==None):
        return x+y
    else:
        return x+y+z
    
print(add_numbers(2,3,z=True,flag=True))

Flag is true!
6


<br>
Assign function `add_numbers` to variable `a`.

In [9]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

3

In [10]:
def add_numbers(x,y,z):
    return x+y+z

a=add_numbers
print(a(1,2,3))

6


<br>
# The Python Programming Language: Types and Sequences

<br>
Use `type` to return the object's type.

In [ ]:
type('This is a string')

In [1]:
type("janunayak")

str

In [2]:
type(None)

NoneType

In [3]:
type(None)

NoneType

In [4]:
type(1)

int

In [5]:
type(1.0)

float

In [6]:
type(add_numbers)

NameError: name 'add_numbers' is not defined

<br>
Tuples are an immutable data structure (cannot be altered).

In [7]:
x = (1, 'a', 2, 'b')
type(x)

tuple

In [8]:
x=(1,'a',3,'janu')
print(x)

(1, 'a', 3, 'janu')


In [9]:
type(x)

tuple

<br>
Lists are a mutable data structure.

In [10]:
x = [1, 'a', 2, 'b']
type(x)

list

In [11]:
x=[1,'janu',2,'nayak','nenavath']
x


[1, 'janu', 2, 'nayak', 'nenavath']

In [12]:
type(x)

list

In [13]:
x.append('naik')

In [14]:
print(x)

[1, 'janu', 2, 'nayak', 'nenavath', 'naik']


<br>
Use `append` to append an object to a list.

In [15]:
x.append(3.3)
print(x)

[1, 'janu', 2, 'nayak', 'nenavath', 'naik', 3.3]


In [16]:
for i in x:
    print(i)

1
janu
2
nayak
nenavath
naik
3.3


In [19]:
len(x)

7

<br>
This is an example of how to loop through each item in the list.

In [17]:
for item in x:
    print(item)

1
janu
2
nayak
nenavath
naik
3.3


<br>
Or using the indexing operator:

In [18]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
janu
2
nayak
nenavath
naik
3.3


In [23]:
list=[1,'nenavath',2.0,'janu',0.3,'nayak']
print(list)
print(len(list))
for i in list:
    print(i)
    
x=0
while(x!=len(i)):
    print(i[x])
    x=x+1

[1, 'nenavath', 2.0, 'janu', 0.3, 'nayak']
6
1
nenavath
2.0
janu
0.3
nayak
n
a
y
a
k


<br>
Use `+` to concatenate lists.

In [24]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [25]:
[3,4,5]+ [6,7,8]

[3, 4, 5, 6, 7, 8]

In [26]:
[3,4]+ [1,2,3,4]

[3, 4, 1, 2, 3, 4]

In [27]:
['janu','nayak'] + ['nenavath']

['janu', 'nayak', 'nenavath']

<br>
Use `*` to repeat lists.

In [29]:
['naik']*['nayak']

TypeError: can't multiply sequence by non-int of type 'list'

In [30]:
[1]*3

[1, 1, 1]

In [31]:
[2]*[3]

TypeError: can't multiply sequence by non-int of type 'list'

In [32]:
['janu']*3

['janu', 'janu', 'janu']

In [33]:
[8]*4

[8, 8, 8, 8]

<br>
Use the `in` operator to check if something is inside a list.

In [34]:
1 in [1, 2, 3]

True

In [35]:
'janu' in 'nenavathjanu'

True

In [36]:
'cat' in 'ract'

False

<br>
Now let's look at strings. Use bracket notation to slice a string.

In [37]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters


T
T
Th


In [38]:
x='janunayaknenavath'
print(x[0])

j


<br>
This will return the last element of the string.

In [39]:
print(x[0:8])

janunaya


In [40]:
print(x[0:9])

janunayak


In [41]:
print(x[-1])

h


In [42]:
print(x[-1:])

h


In [45]:
print(x[:-1:2])

jnnykeaa


In [46]:
print(x[0:])

janunayaknenavath


In [43]:
x[-1]

'h'

In [47]:
print(x[-4:-2])#this will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end

va


In [48]:
print(x[:4])

janu


<br>
This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [ ]:
x[-4:-2]

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [ ]:
x[:3]

<br>
And this is a slice starting from the 4th element of the string and going all the way to the end.

In [49]:
x[3:]

'unayaknenavath'

In [50]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)


Christopher Brooks
ChristopherChristopherChristopher
True


In [51]:
firstname='Janunayak'
lastname='Nenavath'

print(firstname+' '+lastname)
print(firstname*5)
print('nayak' in firstname)

Janunayak Nenavath
JanunayakJanunayakJanunayakJanunayakJanunayak
True


<br>
`split` returns a list of all the words in a string, or a list split on a specific character.

In [52]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


In [64]:
firstname="Janunayak Nenavath Learning python in Coursera".split(' ')[0]
lastname="Janunayak Nenavath Learning python in Coursera".split(' ')[-1]
print(firstname + ' '+lastname)
print(firstname)
print(lastname)

Janunayak Coursera
Janunayak
Coursera


<br>
Make sure you convert objects to strings before concatenating.

In [65]:
'Chris' + 2

TypeError: must be str, not int

In [66]:
'Chris' + str(2)

'Chris2'

In [67]:
'nayak'+2

TypeError: must be str, not int

In [68]:
'nayak'+str(2)

'nayak2'

<br>
Dictionaries associate keys with values.

In [69]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator


'brooksch@umich.edu'

In [81]:
dict={'Janu':10,'nayak':15,'nenavath':20}
print(dict['Janu'])
dict['Janu']
dict['nayak']='NENAVATH'
#print(dict[15])
print(dict)

10
{'Janu': 10, 'nayak': 'NENAVATH', 'nenavath': 20}


In [83]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

<br>
Iterate over all of the keys:

In [84]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


In [85]:
for key in dict:
    print(dict[key])

10
NENAVATH
20


In [86]:
for value in dict:
    print(dict[value])

10
NENAVATH
20


<br>
Iterate over all of the values:

In [1]:
for email in x.values():
    print(email)

NameError: name 'x' is not defined

In [90]:
for key,value in dict.items():
    print(key)
    print(value)

Janu
10
nayak
NENAVATH
nenavath
20


In [88]:
for email in dict.values():
    print(email)

10
NENAVATH
20


<br>
Iterate over all of the items in the list:

In [89]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


In [92]:
for name,value in dict.items():
    print(name +' '+str(value))

Janu 10
nayak NENAVATH
nenavath 20


<br>
You can unpack a sequence into different variables:

In [93]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [94]:
fname

'Christopher'

In [95]:
lname

'Brooks'

In [96]:
a=('janu','nayak','nenavath','GRIET')
firstname,lastname,surname,college=a
print(firstname)
print(lastname)
print(surname)
print(college)

janu
nayak
nenavath
GRIET


<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [97]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

ValueError: too many values to unpack (expected 3)

<br>
# The Python Programming Language: More on Strings

In [98]:
print('Chris' + 2)

TypeError: must be str, not int

In [99]:
print('Chris' + str(2))

Chris2


<br>
Python has a built in method for convenient string formatting.

In [100]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


In [102]:
sales_record={'price':3.24,'num_items':4,'person':'Chris'}
sales_statement='{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],sales_record['num_items'],sales_record['price'],sales-record['num_items']*sales_record['price']))

NameError: name 'sales' is not defined

<br>
# Reading and Writing CSV files

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [31]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

<br>
`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [3]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg= list(csv.DictReader(csvfile))
    
mpg[:5] #the first five dictionaries in our list

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [7]:
len(mpg)

234

In [5]:
len(mpg)

234

In [6]:
len(mpg)

234

<br>
`keys` gives us the column names of our csv.

In [8]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [9]:
mpg[1].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [10]:
mpg[0].values()

odict_values(['1', 'audi', 'a4', '1.8', '1999', '4', 'auto(l5)', 'f', '18', '29', 'p', 'compact'])

In [11]:
mpg[0].items()

odict_items([('', '1'), ('manufacturer', 'audi'), ('model', 'a4'), ('displ', '1.8'), ('year', '1999'), ('cyl', '4'), ('trans', 'auto(l5)'), ('drv', 'f'), ('cty', '18'), ('hwy', '29'), ('fl', 'p'), ('class', 'compact')])

<br>
This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [12]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [13]:
sum(float(d['cty']) for d in mpg)/len(mpg) 

16.86

<br>
Similarly this is how to find the average hwy fuel economy across all cars.

In [14]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [22]:
sum(float(d['manufacturer']) for d in mpg) /len(mpg)

ValueError: could not convert string to float: 'audi'

In [23]:
sum(float(d['model']) for d in mpg)/len(mpg)

ValueError: could not convert string to float: 'a4'

<br>
Use `set` to return the unique values for the number of cylinders the cars in our dataset have.

In [24]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [26]:
manufature=set(d['manufacturer'] for d in mpg) #manufacturer of the cars
manufature

{'audi',
 'chevrolet',
 'dodge',
 'ford',
 'honda',
 'hyundai',
 'jeep',
 'land rover',
 'lincoln',
 'mercury',
 'nissan',
 'pontiac',
 'subaru',
 'toyota',
 'volkswagen'}

In [27]:
models=set(d['model'] for d in mpg) #car models
print(models)

{'forester awd', 'maxima', 'camry', 'grand prix', 'c1500 suburban 2wd', 'impreza awd', 'dakota pickup 4wd', 'jetta', 'toyota tacoma 4wd', 'pathfinder 4wd', 'land cruiser wagon 4wd', 'new beetle', 'altima', 'malibu', 'mountaineer 4wd', 'grand cherokee 4wd', 'a6 quattro', 'navigator 2wd', 'sonata', '4runner 4wd', 'ram 1500 pickup 4wd', 'tiburon', 'f150 pickup 4wd', 'explorer 4wd', 'k1500 tahoe 4wd', 'corvette', 'camry solara', 'range rover', 'a4 quattro', 'civic', 'gti', 'caravan 2wd', 'mustang', 'passat', 'a4', 'expedition 2wd', 'durango 4wd', 'corolla'}


In [28]:
years=set(d['year'] for d in mpg) #year of the car
print(years)

{'1999', '2008'}


In [30]:
tran=set(d['trans'] for d in mpg) #transmission of the car
print(tran)

{'auto(s6)', 'auto(l6)', 'auto(l5)', 'manual(m6)', 'auto(s4)', 'auto(l4)', 'manual(m5)', 'auto(av)', 'auto(l3)', 'auto(s5)'}


<br>
Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [32]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [33]:
CtyMpByCyl=[]

for c in cylinders: #iterate over all the cylinder levels
    summpg=0
    cyltypecount=0
    for d in mpg: #iterate over all dictionaries 
        if d['cyl']==c: #if cylinder type is matches
            summpg=summpg+float(d['cty']) #adding city mpg
            cyltypecount=cyltypecount+1
    CtyMpByCyl.append((c,summpg/cyltypecount))
    
CtyMpByCyl.sort(key=lambda x: x[0])
print(CtyMpByCyl)

[('4', 21.012345679012345), ('5', 20.5), ('6', 16.21518987341772), ('8', 12.571428571428571)]


<br>
Use `set` to return the unique values for the class types in our dataset.

In [34]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

<br>
And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [35]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

<br>
# The Python Programming Language: Dates and Times

In [63]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [64]:
tm.time()

1568369356.75

<br>
Convert the timestamp to datetime.

In [65]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 9, 13, 10, 9, 21, 400744)

<br>
Handy datetime attributes:

In [66]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2019, 9, 13, 10, 9, 21)

<br>
`timedelta` is a duration expressing the difference between two dates.

In [67]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(100)

<br>
`date.today` returns the current local date.

In [68]:
today = dt.date.today()

In [69]:
today - delta # the date 100 days ago

datetime.date(2019, 6, 5)

In [70]:
today > today-delta # compare dates

True

In [36]:
import datetime as dt
import time as tm

In [37]:
dt.datatime()

AttributeError: module 'datetime' has no attribute 'datatime'

In [38]:
tm.time()


1568368091.99

In [42]:
dtnow =dt.datetime.fromtimestamp(tm.time()) #converting timestamp to datetime
print(dtnow)

2019-09-13 09:50:54.463699


In [43]:
dtnow.year,dtnow.month,dtnow.day

(2019, 9, 13)

In [45]:
dtnow.hour,dtnow.minute,dtnow.second

(9, 50, 54)

In [51]:
delta=dt.timedelta(days=100)
print(delta)

100 days, 0:00:00


In [56]:
today=dt.date.today()
print(today)

2019-09-13


In [61]:
print(today-delta)

2019-06-05


In [62]:
today > today-delta

True

In [2]:
people=['Dr.christopher Brooks','Dr.keven collins-thompson','Dr.vG vinod','JanuNayak']

def split_title_and_name(person):
    title=person.split()[0]
    lastname=person.split()[-1]
    return '{} {}'.format(title,lastname)
    

list(map(split_title_and_name,people))

['Dr.christopher Brooks',
 'Dr.keven collins-thompson',
 'Dr.vG vinod',
 'JanuNayak JanuNayak']

In [3]:
people=["Janunayak","Sureshnayak","Shivanayak","Vinodnayak"]

def faculty(names):
    firstname=names.split()[0]
    lastname=names.split()[-1]
    return '{} {}'.format(firstname,lastname)

list(map(faculty,people))

['Janunayak Janunayak',
 'Sureshnayak Sureshnayak',
 'Shivanayak Shivanayak',
 'Vinodnayak Vinodnayak']

<br>
# The Python Programming Language: Objects and map()

<br>
An example of a class in python:

In [4]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [5]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


In [6]:
class Person:
    department="School of Information" #a class variable
    
    def set_name(self,new_name): #method
        self.name=new_name
    def set_location(self,new_location):
        self.location=new_location
        

In [10]:
person=Person()
person.set_name("Janunayak")
person.set_location("Nalgonda")
print('{} live in {} and works in the department {}'.format(person.name,person.location,person.department))

Janunayak live in Nalgonda and works in the department School of Information


In [13]:
class Student:
    college='GRIET' #a class variable
    
    def set_name(self,new_name):
        self.name=new_name
    def set_rollno(self,new_rollno):
        self.rollno=new_rollno
        
student=Student()
student.set_name("JANUNAYAK")
student.set_rollno("17241A1243")
print('{} rollno is {} and student at {} college'.format(student.name,student.rollno,student.college))

JANUNAYAK rollno is 17241A1243 and student at GRIET college


<br>
Here's an example of mapping the `min` function between two lists.

In [14]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [15]:
student1=[30,40,50,60]
student2=[10,10,30,70]
marks=map(min,student1,student2)
print(marks)

In [16]:
for i in marks:
    print(i)

10
10
30
60


<br>
Now let's iterate through the map object to see the values.

In [17]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [18]:
student=[100,99,98,100,90,70]
student3=[100,100,100,100,100,50]
marks=map(max,student,student3)
marks
for m in marks:
    print(m)

100
100
100
100
100
70


<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [1]:
my_function = lambda a, b, c : a + b

In [2]:
my_function(1, 2, 3)

3

In [5]:
my_function=lambda a,b,c:a+b

my_function(1,2,3)

3

In [7]:
nayak=lambda a,b,c:a+b+c

In [8]:
nayak(1,2,3)

6

In [10]:
naik=lambda a,b,c:a+b
naik(5,6,7)

11

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [11]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
Now the same thing but with list comprehension.

In [12]:
list=[]
for i in range(0,100):
    if i%2==0:
        list.append(i)
list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [13]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [14]:
list=[i for i in range(0,100) if i%2==0]
list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [15]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [16]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [17]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [18]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [19]:
m.shape

(2, 3)

<br>
`arange` returns evenly spaced values within a given interval.

In [20]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [21]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [22]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [44]:
k=np.linspace(0,4,9)
k

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [46]:
s=np.linspace(0,3,3)
s

array([ 0. ,  1.5,  3. ])

<br>
`resize` changes the shape and size of array in-place.

In [23]:
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [24]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [47]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [48]:
np.zeros((2,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [50]:
np.twos((3,3))

AttributeError: module 'numpy' has no attribute 'twos'

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [25]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [26]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [27]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

<br>
Create an array using repeating list (or see `np.tile`)

In [28]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [29]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
#### Combining Arrays

In [30]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [31]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [32]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [ ]:
import numpy as np

In [33]:
list=[1,2,3]
x=np.array(list)
x

array([1, 2, 3])

In [35]:
y=np.array([6,7,8])
y

array([6, 7, 8])

In [37]:
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
m.shape

(2, 3)

In [40]:
x=np.arange(0,30,2) #start at 0 and every times count by 2
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [42]:
x=x.reshape(3,5)
x

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [51]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [53]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [52]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[[  0   4  16  36  64]
 [100 144 196 256 324]
 [400 484 576 676 784]]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [54]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

ValueError: shapes (3,5) and (3,) not aligned: 5 (dim 1) != 3 (dim 0)

In [56]:
x=[1,2,3]
y=[4,5,6]
x+y

[1, 2, 3, 4, 5, 6]

In [57]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [58]:
z = np.array([y, y**2])
z

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

<br>
The shape of array `z` is `(2,3)` before transposing.

In [60]:
z.shape

NameError: name 'z' is not defined

<br>
Use `.T` to get the transpose.

In [61]:
z.T

NameError: name 'z' is not defined

<br>
The number of rows has swapped with the number of columns.

In [ ]:
z.T.shape

<br>
Use `.dtype` to see the data type of the elements in the array.

In [ ]:
z.dtype

<br>
Use `.astype` to cast to a specific type.

In [ ]:
z = z.astype('f')
z.dtype

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [ ]:
a = np.array([-4, -2, 1, 3, 5])

In [ ]:
a.sum()

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.mean()

In [ ]:
a.std()

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [ ]:
a.argmax()

In [ ]:
a.argmin()

<br>
## Indexing / Slicing

In [62]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [63]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [64]:
s[1:5]

array([ 1,  4,  9, 16])

<br>
Use negatives to count from the back.

In [65]:
s[-4:]

array([ 81, 100, 121, 144])

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [66]:
s[-5::-2]

array([64, 36, 16,  4,  0])

<br>
Let's look at a multidimensional array.

In [67]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`

In [68]:
r[2, 2]

14

<br>
And use : to select a range of rows or columns

In [69]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [70]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [71]:
r[-1, ::2]

array([30, 32, 34])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [72]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [73]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [74]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [75]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [76]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [77]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [78]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [79]:
test = np.random.randint(0, 10, (4,3))
test

array([[4, 0, 4],
       [3, 0, 5],
       [0, 9, 2],
       [5, 1, 3]])

<br>
Iterate by row:

In [80]:
for row in test:
    print(row)

[4 0 4]
[3 0 5]
[0 9 2]
[5 1 3]


<br>
Iterate by index:

In [81]:
for i in range(len(test)):
    print(test[i])

[4 0 4]
[3 0 5]
[0 9 2]
[5 1 3]


<br>
Iterate by row and index:

In [82]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [4 0 4]
row 1 is [3 0 5]
row 2 is [0 9 2]
row 3 is [5 1 3]


In [86]:
for j,row in enumerate(test):
    print('row', j, 'is',row)

row 0 is [4 0 4]
row 1 is [3 0 5]
row 2 is [0 9 2]
row 3 is [5 1 3]


In [87]:
for k in enumerate(test):
    print(k)

(0, array([4, 0, 4]))
(1, array([3, 0, 5]))
(2, array([0, 9, 2]))
(3, array([5, 1, 3]))


<br>
Use `zip` to iterate over multiple iterables.

In [83]:
test2 = test**2
test2

array([[16,  0, 16],
       [ 9,  0, 25],
       [ 0, 81,  4],
       [25,  1,  9]])

In [84]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[4 0 4] + [16  0 16] = [20  0 20]
[3 0 5] + [ 9  0 25] = [12  0 30]
[0 9 2] + [ 0 81  4] = [ 0 90  6]
[5 1 3] + [25  1  9] = [30  2 12]


In [85]:
for i,j in zip(test,test2):
    print(i, '+',j, '=',i+j)

[4 0 4] + [16  0 16] = [20  0 20]
[3 0 5] + [ 9  0 25] = [12  0 30]
[0 9 2] + [ 0 81  4] = [ 0 90  6]
[5 1 3] + [25  1  9] = [30  2 12]
